name: CI

on:
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master 
        with:
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          source-repo: git@github.com:qytayh/varlet-ui-pro.git
          destination-repo: git@gitee.com:qytayh/varlet-ui-pro.git
